### ISSUE TITLE
error in installing

### ISSUE THREAD

**Issue by sanj0212** [yuchsiao/caplet#1]
Getting following error in installing.. Kindly suggest what to do..
----------------------------------------------------------
mpic++ -Wall -Iinclude -O2 -DCAPLET_MPI -c src/caplet_widgets.cpp -o obj/mpi/caplet_widgets.o
src/caplet_widgets.cpp:46:101: error: redeclaration of ‘template<class T> void caplet::print_matrix(T*, int, int, std::__cxx11::string, char, std::ostream&)’ may not have default arguments [-fpermissive]
 void print_matrix(T* A, int m, int n, const std::string name, char uplo, std::ostream &out=std::cout){
                                                                                                     ^
Makefile:39: recipe for target 'obj/mpi/caplet_widgets.o' failed
make: *** [obj/mpi/caplet_widgets.o] Error 1

**Comment by yuchsiao** [comment]
Which gcc in your system?

**Comment by sanj0212** [comment]
gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4)

**Comment by yuchsiao** [comment]
gcc 5 adopts more recent standard that changes some rules of template declaration. I have added a flag -fpermissive to allow the compilation. Please pull again to give it a try and let me know if that solves the issue.

**Comment by sanj0212** [comment]
Thanks a lot.. it worked.  I could install the program and test example run also giving results.
Many thanks..
